name: Backports

on:
  issues:
    types: [labeled] # triggered when any label is added to an issue

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'version/v0' }}
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const parentIssue = context.issue;
            const parentIssueTitle = context.payload.issue.title;
            const parentIssueNumber = parentIssue.number;

            // Create the sub-issue
            const newIssue = await github.rest.issues.create({
              owner: parentIssue.owner,
              repo: parentIssue.repo,
              title: `Backport #" + parentIssueNumber + " to release/v0`,
              body: `"Backport #" + parentIssueNumber + " to release/v0`
            });

            const subIssueId = newIssue.data.id;

            // Attach the sub-issue to the parent
            await github.rest.issues.addSubIssue({
              owner: parentIssue.owner,
              repo: parentIssue.repo,
              issue_number: parentIssueNumber,
              sub_issue_id: subIssueId
            });
