name: Backports
# This workflow generates "backport" issues when a release branch label is added to an issue
on:
  issues:
    types: [labeled] # triggered when any label is added to an issue

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'version/v0' }}
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const parentIssue = context.payload.issue;
            const parentIssueTitle = parentIssue.title;
            const parentIssueNumber = parentIssue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            // Get terraform-maintainers team
            const { data: teamMembers } = await github.rest.teams.listMembersInOrg({
              org: "rancher",
              team_slug: "terraform-maintainers"
            });
            const newAssignees = teamMembers.map(member => member.login);

            // Create the sub-issue
            const newIssue = await github.rest.issues.create({
              owner: owner,
              repo: repo,
              title: "Backport #" + parentIssueNumber + " to release/v0",
              body:  "Backport #" + parentIssueNumber + " to release/v0",
              labels: ['release/v0'],
              assignees: newAssignees // assign terraform-maintainers to sub-issue
            });

            const subIssueId = newIssue.data.id;

            // Attach the sub-issue to the parent using API request
            await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/sub_issues', {
              owner: owner,
              repo: repo,
              issue_number: parentIssueNumber,
              sub_issue_id: subIssueId,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
