name: 'Auto Cherry-Pick to Release Branches'

on:
  push:
    branches:
      - 'main'

jobs:
  create-cherry-pick-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read 

    steps:
      - name: 'Wait for merge to settle'
        run: sleep 10
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Find Issues and Create Cherry-Pick PRs'
        uses: actions/github-script@v7
        with:
          script: |
            const execSync = require('child_process').execSync;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const mergeCommitSha = context.payload.head_commit.id;

            const { data: associatedPrs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: mergeCommitSha,
            });
            const pr = associatedPrs.find(p => p.base.ref === 'main' && p.merged_at);
            if (!pr) {
              core.info(`No merged PR found for commit ${mergeCommitSha}. This may have been a direct push. Exiting.`);
              return;
            }
            core.info(`Found associated PR: #${pr.number}`);

            // https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests
            core.info(`Searching for 'internal/main' issue linked to PR #${pr.number}`);
            const { data: searchResults } = await github.request('GET /search/issues', {
              q: `is:issue label:"internal/main" repo:${owner}/${repo} in:body #${pr.number}`,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            if (searchResults.data.total_count === 0) {
              core.info(`No 'internal/main' issue found for PR #${pr.number}. Exiting.`);
              return;
            }
            const mainIssue = searchResults.data.items[0];
            core.info(`Found main issue: #${mainIssue.number}`);

            // https://docs.github.com/en/rest/issues/sub-issues?apiVersion=2022-11-28#add-sub-issue
            core.info(`Fetching sub-issues for main issue #${mainIssue.number}`);
            const { data: subIssues } = await github.request('GET /repos/{owner}/{repo}/issues/{issue_number}/sub-issues', {
              owner: owner,
              repo: repo,
              issue_number: mainIssue.number,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            if (subIssues.length === 0) {
              core.info(`No sub-issues found for issue #${mainIssue.number}. Exiting.`);
              return;
            }
            core.info(`Found ${subIssues.length} sub-issues.`);

            for (const subIssue of subIssues) {
              const subIssueNumber = subIssue.number;
              // Find the release label directly on the sub-issue object
              const releaseLabel = subIssue.labels.find(label => label.name.startsWith('release/v'));
              if (!releaseLabel) {
                core.warning(`Sub-issue #${subIssueNumber} has no 'release/v...' label. Skipping.`);
                continue;
              }
              const targetBranch = releaseLabel.name
              core.info(`Processing sub-issue #${subIssueNumber} for target branch: ${targetBranch}`);
              const newBranchName = `backport-${pr.number}-${targetBranch.replace(/\//g, '-')}`;
              execSync(`git config user.name "github-actions[bot]"`);
              execSync(`git config user.email "github-actions[bot]@users.noreply.github.com"`);
              execSync(`git fetch origin ${targetBranch}`);
              execSync(`git checkout -b ${newBranchName} origin/${targetBranch}`);
              execSync(`git cherry-pick -x ${mergeCommitSha}`);
              execSync(`git push origin ${newBranchName}`);

              core.info(`Creating pull request for branch ${newBranchName} targeting ${targetBranch}...`);
              const { data: newPr } = await github.rest.pulls.create({
                owner,
                repo,
                title: pr.title,
                head: newBranchName,
                base: targetBranch,
                body: "This pull request cherry-picks the changes from #" + pr.number + " into " + targetBranch,
                assignees: ['terraform-maintainers']
              });
            }
