name: Backports

on:
  issues:
    types: [labeled] # triggered when any label is added to an issue

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'version/v0' }}
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const parentIssue = context.payload.issue;
            const parentIssueTitle = parentIssue.title;
            const parentIssueNumber = parentIssue.number;
            const repo = parentIssue.repo;
            const owner = parentIssue.owner;

            // Create the sub-issue
            const newIssue = await github.rest.issues.create({
              owner: owner,
              repo: repo,
              title: "Backport #" + parentIssueNumber + " to release/v0",
              body:  "Backport #" + parentIssueNumber + " to release/v0"
            });

            const subIssueId = newIssue.data.id;

            // Attach the sub-issue to the parent using API request
            await github.request('POST /repos/{owner}/{repo}/issues/{parentIssueNumber}/sub_issues', {
              owner: owner,
              repo: repo,
              issue_number: parentIssueNumber,
              sub_issue_id: subIssueId,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
