name: MainIssue
# This workflow generates a "main" issue when a PR is created targeting main.
on:
  pull_request_target:
    branches: [main]
    types: [opened]

jobs:
  generate-issue:
    name: 'Create Main Issue'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const pr = context.payload.pull_request;
            const newLabels = ['internal/main'];
            const releaseLabel = pr.labels.find(label => label.name.startsWith('release/v'));
            if (releaseLabel) {
              const versionLabel = releaseLabel.name.replace('release/', 'version/');
              newLabels.push(versionLabel);
            }
            // Note: can't get terraform-maintainers team, the default token can't access org level objects
            // Create the main issue
            // https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue
            // Note: issues can't have teams assigned to them
            const newIssue = await github.rest.issues.create({
              owner: owner,
              repo: repo,
              title: pr.title,
              body:  "This is the main issue tracking #" + pr.number + " \n\n" +
                "Please add labels indicating the release versions eg. 'version/v0' \n\n" +
                "Please add comments for user issues which this issue addresses. \n\n" +
                "Description copied from PR: \n" + pr.body,
              labels: newLabels,
              assignees: ['matttrach']
            });
